import json


DEFAULT_RESPONSE = {

    "issue": "",

    "severity": "Unknown",

    "confidence": 0.0,

    "rights": "",

    "explanation": "",

    "options": [],

    "recommended_option": "",

    "recommendation_reason": "",

    "risk_level": "Unknown",

    "required_documents": [],

    "next_steps": [],

    "lawyer_needed": False,

    "lawyer_specialization": "",

    "recommended_lawyers": [],

    "sources": [],

    "disclaimer":
    "This response is generated by AI and should not replace professional legal advice."
}


def validate_response(response):

    # If Gemma returns a string,
    # convert it into JSON

    if isinstance(response, str):

        response = json.loads(response)

    # Fill missing fields

    for key, value in DEFAULT_RESPONSE.items():

        if key not in response:

            response[key] = value

    return response